# Generated by Django 6.0.5 on 2026-05-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0004_review"),
        ("patient", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        max_length=50,
                        verbose_name=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Running", "Running"),
                        ],
                    ),
                ),
                (
                    "appointment_status",
                    models.CharField(
                        default="Pending",
                        max_length=50,
                        verbose_name=[("Offline", "Offline"), ("Online", "Online")],
                    ),
                ),
                ("symptom", models.TextField(max_length=100)),
                ("cancel", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "time",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.availabletime",
                    ),
                ),
            ],
        ),
    ]
