# Generated by Django 6.0.5 on 2026-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_status",
            field=models.CharField(
                choices=[("Offline", "Offline"), ("Online", "Online")],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Running", "Running"),
                ],
                max_length=10,
            ),
        ),
    ]
