# Generated by Django 6.0.5 on 2026-05-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_appointment_status_and_more"),
        ("doctor", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.availabletime"
            ),
        ),
    ]
