# Generated by Django 6.0.5 on 2026-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractus",
            options={"verbose_name_plural": "contract us"},
        ),
    ]
