# Generated by Django 6.0.5 on 2026-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="available_time",
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_time",
            field=models.ManyToManyField(to="doctor.availabletime"),
        ),
    ]
