# Generated by Django 6.0.5 on 2026-05-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_doctor_available_time_doctor_available_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="speacialization",
            new_name="specialization",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.designation",
            ),
        ),
    ]
