# Generated by Django 6.0.5 on 2026-05-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_rename_speacialization_doctor_specialization_and_more"),
        ("patient", "0002_alter_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=30)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("⭐", "⭐"),
                            ("⭐⭐", "⭐⭐"),
                            ("⭐⭐⭐", "⭐⭐⭐"),
                            ("⭐⭐⭐⭐", "⭐⭐⭐⭐"),
                            ("⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"),
                        ]
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
                (
                    "reviewers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
